<?php declare(strict_types=1); ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Barangay Issuance Settings</title>
  <script src="https://kit.fontawesome.com/3482e00999.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="<?= htmlspecialchars(appUrl('CSS-Styles/Admin-End-CSS/AdminDashboardStyle.css')) ?>">
  <style>
    :root{--is-accent:#de710c;--is-accent-dark:#a95305;--is-ink:#202631;--is-muted:#68707d;--is-line:#eadfd4;--is-soft:#fff8f1;--is-bg:#f7f8fa;--is-success:#16845b}
    body{background:var(--is-bg)}
    .is-page{max-width:1240px;margin:0 auto}.is-title{font-family:'Charis SIL Bold',serif;color:var(--is-accent);font-size:clamp(1.85rem,3vw,2.55rem);line-height:1.1}.is-lead{color:var(--is-muted);max-width:820px}
    .is-hero{position:relative;overflow:hidden;border:1px solid #f0ddca;border-radius:24px;background:linear-gradient(135deg,#fff 0%,#fff9f2 100%);padding:1.55rem 1.65rem;box-shadow:0 12px 35px rgba(75,48,21,.06)}
    .is-hero:after{content:"";position:absolute;width:230px;height:230px;border-radius:50%;right:-80px;top:-120px;background:rgba(222,113,12,.08)}
    .is-hero-actions{position:relative;z-index:1}.is-summary{display:flex;gap:.65rem;flex-wrap:wrap;margin-top:1rem}.is-summary-chip{display:inline-flex;align-items:center;gap:.45rem;padding:.48rem .75rem;border:1px solid #eadfd4;border-radius:999px;background:#fff;color:#515a67;font-size:.84rem;font-weight:700}.is-summary-chip i{color:var(--is-accent)}
    .is-section{scroll-margin-top:95px;border:1px solid var(--is-line);border-radius:22px;background:#fff;box-shadow:0 8px 24px rgba(27,36,48,.045);margin-bottom:1rem;overflow:hidden}.is-section-head{display:flex;gap:.9rem;align-items:flex-start;padding:1.15rem 1.25rem;border-bottom:1px solid #eee8e2;background:linear-gradient(180deg,#fffaf5,#fff)}.is-section-icon{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;flex:0 0 auto;background:#ffead6;color:var(--is-accent-dark)}.is-section-title{font-size:1.05rem;font-weight:800;color:var(--is-ink);margin:0}.is-section-copy{color:var(--is-muted);font-size:.88rem;margin:.2rem 0 0}.is-section-body{padding:1.25rem}
    .is-toggle-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem}.is-toggle{display:flex;align-items:flex-start;gap:.8rem;padding:.95rem 1rem;border:1px solid #e8ebef;border-radius:15px;background:#fbfcfd;cursor:pointer;transition:.18s}.is-toggle:hover{border-color:#e5bd98;background:#fffaf6}.is-toggle .form-check-input{width:2.55rem;height:1.35rem;margin:.08rem 0 0;flex:0 0 auto}.is-toggle .form-check-input:checked{background-color:var(--is-accent);border-color:var(--is-accent)}.is-toggle-title{display:block;font-size:.92rem;font-weight:800;color:var(--is-ink)}.is-toggle-copy{display:block;color:var(--is-muted);font-size:.79rem;margin-top:.15rem}
    .is-validity{display:grid;grid-template-columns:minmax(210px,.65fr) minmax(0,1.35fr);gap:1rem;margin-top:1rem}.is-field{padding:1rem;border:1px solid #e8ebef;border-radius:15px}.is-field-label{font-weight:800;color:#303743;font-size:.88rem}.is-field-copy{color:var(--is-muted);font-size:.78rem;margin:.2rem 0 .75rem}.is-days{display:flex;gap:.5rem;flex-wrap:wrap}.is-day input{position:absolute;opacity:0;pointer-events:none}.is-day span{display:inline-flex;align-items:center;justify-content:center;min-width:76px;padding:.55rem .7rem;border:1px solid #dfe3e8;border-radius:10px;background:#fff;color:#515966;font-size:.84rem;font-weight:700;cursor:pointer}.is-day input:checked+span{color:#9d4b00;border-color:#f0b77f;background:#fff0e1;box-shadow:inset 0 0 0 1px #f3c393}
    .is-cert-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.is-cert{border:1px solid #e6e9ed;border-radius:17px;background:#fff;overflow:hidden}.is-cert-top{display:flex;align-items:center;justify-content:space-between;gap:.8rem;padding:.9rem 1rem;background:#fafbfc;border-bottom:1px solid #edf0f2}.is-cert-name{font-size:.91rem;font-weight:800;color:var(--is-ink)}.is-cert .form-check-input:checked{background-color:var(--is-success);border-color:var(--is-success)}.is-cert-body{padding:1rem}.is-options{min-height:132px;resize:vertical;font-size:.86rem;line-height:1.45;background:#fcfcfd}.is-options:focus{border-color:#e9a968;box-shadow:0 0 0 .2rem rgba(222,113,12,.11)}
    .is-notification{display:grid;grid-template-columns:190px minmax(0,1fr);gap:1rem;padding:1rem 0;border-bottom:1px solid #edf0f2}.is-notification:first-child{padding-top:0}.is-notification:last-child{border-bottom:0;padding-bottom:0}.is-message{min-height:72px;resize:vertical;font-size:.87rem}.is-placeholder{display:flex;gap:.4rem;flex-wrap:wrap;margin-bottom:1rem}.is-placeholder code{color:#8d490c;background:#fff0df;border:1px solid #f1d2b4;border-radius:7px;padding:.3rem .5rem;font-size:.76rem}
    .is-aging{margin-top:1.2rem;padding:1rem;border:1px solid #f1d5b7;border-radius:16px;background:#fff8ef}.is-aging-grid{display:grid;grid-template-columns:180px minmax(0,1fr);gap:1rem;margin-top:.8rem}
    .is-sign-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.is-upload{grid-column:1/-1;padding:1rem;border:1px dashed #d8dde3;border-radius:14px;background:#fafbfc}
    .is-savebar{position:sticky;bottom:.75rem;z-index:25;display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:.8rem .9rem .8rem 1rem;border:1px solid #ead6c2;border-radius:16px;background:rgba(255,255,255,.96);box-shadow:0 12px 35px rgba(40,32,24,.15);backdrop-filter:blur(10px)}.is-save-note{color:var(--is-muted);font-size:.83rem}.btn-is-primary{color:#fff;background:var(--is-accent);border-color:var(--is-accent);font-weight:750}.btn-is-primary:hover{color:#fff;background:var(--is-accent-dark);border-color:var(--is-accent-dark)}
    @media(max-width:900px){.is-toggle-grid,.is-cert-grid,.is-validity{grid-template-columns:1fr}.is-notification{grid-template-columns:1fr;gap:.55rem}.is-aging-grid,.is-sign-grid{grid-template-columns:1fr}.is-upload{grid-column:auto}}
    @media(max-width:576px){.is-hero,.is-section-body{padding:1rem}.is-section-head{padding:1rem}.is-save-note{display:none}.is-savebar .btn{width:100%}.is-hero-actions{width:100%}.is-hero-actions .btn{width:100%}}
  </style>
</head>
<body><div class="d-flex flex-column flex-md-row" style="min-height:100vh"><?php include __DIR__.'/sidebar.php'; ?>
<main class="flex-grow-1 p-3 p-xl-4"><div class="is-page">
  <header class="is-hero"><div class="d-flex justify-content-between align-items-start gap-3 flex-wrap"><div><h1 class="is-title mb-2">Barangay Issuance Settings</h1><p class="is-lead mb-0">Manage certificate availability, validity, verification, resident messages, request choices, and signatory details from one page.</p><div class="is-summary"><span class="is-summary-chip"><i class="fa-solid fa-file-circle-check"></i><?= count(dms_issuance_certificate_catalog()) ?> certificates</span><span class="is-summary-chip"><i class="fa-solid fa-calendar-check"></i><?= (int)$issuanceSettings['default_validity_days'] ?>-day default</span><span class="is-summary-chip"><i class="fa-solid fa-bell"></i>5 resident events</span></div></div><div class="is-hero-actions"><a class="btn btn-outline-secondary" href="<?= htmlspecialchars($documentSettingsBackUrl) ?>"><i class="fa-solid fa-arrow-left me-2"></i>Back to Module</a></div></div></header>
  <?php if ($documentSettingsSuccessMessage !== ''): ?><div class="alert alert-success mt-3 mb-0"><i class="fa-solid fa-circle-check me-2"></i><?= htmlspecialchars($documentSettingsSuccessMessage) ?></div><?php endif; ?>
  <?php if ($documentSettingsErrorMessage !== ''): ?><div class="alert alert-danger mt-3 mb-0"><i class="fa-solid fa-triangle-exclamation me-2"></i><?= htmlspecialchars($documentSettingsErrorMessage) ?></div><?php endif; ?>
  <form method="post" action="<?= htmlspecialchars($documentSettingsActionUrl) ?>" id="issuanceSettingsForm"><?= csrfTokenField() ?><input type="hidden" name="action" value="save_issuance_settings">
    <section class="is-section" id="general"><div class="is-section-head"><span class="is-section-icon"><i class="fa-solid fa-sliders"></i></span><div><h2 class="is-section-title">General issuance controls</h2><p class="is-section-copy">Set the rules applied across online certificate requests and document generation.</p></div></div><div class="is-section-body">
      <div class="is-toggle-grid">
        <?php $toggles=[['online_requests_enabled','Online certificate requests','Allow residents to submit certificate applications online.'],['first_time_job_seeker_exempt','First-Time Job Seeker exemption','Automatically treat eligible first-time job seeker requests as fee-exempt.'],['qr_verification_enabled','QR verification','Add verification details to supported generated certificates.'],['essential_details_only','Essential resident details only','Limit certificate views to information needed for processing.']]; foreach($toggles as [$key,$title,$copy]): ?><label class="is-toggle" for="<?= $key ?>"><input class="form-check-input" type="checkbox" name="<?= $key ?>" id="<?= $key ?>" <?= !empty($issuanceSettings[$key])?'checked':'' ?>><span><span class="is-toggle-title"><?= htmlspecialchars($title) ?></span><span class="is-toggle-copy"><?= htmlspecialchars($copy) ?></span></span></label><?php endforeach; ?>
      </div>
      <div class="is-validity"><div class="is-field"><label class="is-field-label" for="default_validity_days">Default validity</label><p class="is-field-copy">Used when staff do not choose another period.</p><div class="input-group"><input class="form-control" id="default_validity_days" type="number" min="1" max="365" name="default_validity_days" value="<?= (int)$issuanceSettings['default_validity_days'] ?>"><span class="input-group-text">days</span></div></div><div class="is-field"><div class="is-field-label">Allowed validity choices</div><p class="is-field-copy">Choose the periods staff can select during approval and manual issuance.</p><div class="is-days"><?php foreach([3,7,15,30,45,60,90,180,365] as $days): ?><label class="is-day"><input type="checkbox" name="allowed_validity_days[]" value="<?= $days ?>" <?= in_array($days,(array)$issuanceSettings['allowed_validity_days'],true)?'checked':'' ?>><span><?= $days ?> days</span></label><?php endforeach; ?></div></div></div>
    </div></section>

    <section class="is-section" id="certificates"><div class="is-section-head"><span class="is-section-icon"><i class="fa-solid fa-file-lines"></i></span><div><h2 class="is-section-title">Certificates and request choices</h2><p class="is-section-copy">Control availability and customize the purpose dropdown for every supported certificate.</p></div></div><div class="is-section-body"><div class="is-cert-grid">
      <?php foreach(dms_issuance_certificate_catalog() as $key=>$label): $cert=$issuanceSettings['certificates'][$key]??[]; ?><article class="is-cert"><div class="is-cert-top"><span class="is-cert-name"><?= htmlspecialchars($label) ?></span><div class="form-check form-switch m-0"><input class="form-check-input" type="checkbox" name="certificate_enabled[<?= $key ?>]" id="cert_<?= $key ?>" <?= !empty($cert['enabled'])?'checked':'' ?> aria-label="Enable <?= htmlspecialchars($label) ?>"></div></div><div class="is-cert-body"><label class="form-label small fw-bold" for="options_<?= $key ?>">Purpose dropdown options</label><p class="small text-muted mb-2">One option per line. Include “Other” to allow a custom answer.</p><textarea class="form-control is-options" id="options_<?= $key ?>" name="purpose_options[<?= $key ?>]"><?= htmlspecialchars(implode("\n",(array)($cert['purpose_options']??[]))) ?></textarea></div></article><?php endforeach; ?>
    </div></div></section>

    <section class="is-section" id="notifications"><div class="is-section-head"><span class="is-section-icon"><i class="fa-solid fa-bell"></i></span><div><h2 class="is-section-title">Notifications</h2><p class="is-section-copy">Choose which status updates residents receive and customize the message for each event.</p></div></div><div class="is-section-body"><div class="is-placeholder"><code>{request_id}</code><code>{document_type}</code><code>{reason}</code><code>{count}</code><code>{days}</code></div>
      <?php foreach((array)$issuanceSettings['resident_notifications'] as $event=>$notification): ?><div class="is-notification"><div><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="notification_enabled[<?= htmlspecialchars($event) ?>]" id="notify_<?= htmlspecialchars($event) ?>" <?= !empty($notification['enabled'])?'checked':'' ?>><label class="form-check-label fw-bold text-capitalize" for="notify_<?= htmlspecialchars($event) ?>"><?= htmlspecialchars(str_replace('_',' ',$event)) ?></label></div><div class="small text-muted mt-1">Resident status update</div></div><textarea class="form-control is-message" name="notification_message[<?= htmlspecialchars($event) ?>]" maxlength="500" aria-label="<?= htmlspecialchars(str_replace('_',' ',$event)) ?> message"><?= htmlspecialchars((string)$notification['message']) ?></textarea></div><?php endforeach; ?>
      <div class="is-aging"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="aging_notification_enabled" id="aging_notification_enabled" <?= !empty($issuanceSettings['aging_notification_enabled'])?'checked':'' ?>><label class="form-check-label fw-bold" for="aging_notification_enabled">Admin notification for aging requests</label></div><p class="small text-muted mb-0 mt-1">Alert administrators when certificate requests remain pending beyond the threshold.</p><div class="is-aging-grid"><div><label class="form-label small fw-bold" for="aging_days">Threshold</label><div class="input-group"><input class="form-control" id="aging_days" type="number" min="1" max="90" name="aging_days" value="<?= (int)$issuanceSettings['aging_days'] ?>"><span class="input-group-text">days</span></div></div><div><label class="form-label small fw-bold" for="aging_message">Admin message</label><textarea class="form-control" id="aging_message" name="aging_message" rows="2"><?= htmlspecialchars((string)$issuanceSettings['aging_message']) ?></textarea></div></div></div>
    </div></section>

    <div class="is-savebar mb-3"><span class="is-save-note"><i class="fa-solid fa-shield-halved me-2 text-success"></i>Changes are audit logged and apply after saving.</span><button class="btn btn-is-primary px-4" type="submit"><i class="fa-solid fa-floppy-disk me-2"></i>Save Issuance Settings</button></div>
  </form>

  <section class="is-section" id="signatory"><div class="is-section-head"><span class="is-section-icon"><i class="fa-solid fa-signature"></i></span><div><h2 class="is-section-title">Certificate signatory</h2><p class="is-section-copy">The seated official’s identity is synchronized automatically. Upload the signature asset used on generated certificates.</p></div></div><form class="is-section-body" method="post" enctype="multipart/form-data" action="<?= htmlspecialchars($documentSettingsActionUrl) ?>"><?= csrfTokenField() ?><input type="hidden" name="action" value="save_document_module_settings">
    <?php foreach($documentSettingsRows as $row): $key=(string)$row['signatory_key']; ?><div class="is-sign-grid"><div><label class="form-label fw-bold">Signatory name</label><input class="form-control" name="signatory_name_<?= $key ?>" value="<?= htmlspecialchars((string)$row['name']) ?>" <?= $row['source']==='manual'?'':'readonly' ?>></div><div><label class="form-label fw-bold">Official title</label><input class="form-control" name="signatory_title_<?= $key ?>" value="<?= htmlspecialchars((string)$row['title']) ?>" <?= $row['source']==='manual'?'':'readonly' ?>></div><div class="is-upload"><label class="form-label fw-bold">Signature image</label><input class="form-control" type="file" accept="image/png,image/jpeg,image/webp" name="signature_file_<?= $key ?>"><div class="form-text">PNG with a transparent background is recommended.</div></div></div><?php endforeach; ?><div class="text-end mt-3"><button class="btn btn-is-primary px-4"><i class="fa-solid fa-signature me-2"></i>Save Signatory</button></div>
  </form></section>
</div></main></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script></body></html>
