<?php declare(strict_types=1); ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Barangay Issuance Settings</title>
  <script src="https://kit.fontawesome.com/3482e00999.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="<?= htmlspecialchars(appUrl('CSS-Styles/Admin-End-CSS/AdminDashboardStyle.css')) ?>">
  <style>
    .is-title{font-family:'Charis SIL Bold',serif;color:#de710c}.is-shell{max-width:1180px}.is-card{border:1px solid #eadfD3;border-radius:18px;background:#fff;overflow:hidden}.is-head{padding:1rem 1.2rem;background:#fff8f1;border-bottom:1px solid #f0e4d8}.is-body{padding:1.2rem}.is-cert-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.is-cert{border:1px solid #e8eaed;border-radius:14px;padding:1rem}.is-message{min-height:74px}.nav-pills .nav-link.active{background:#de710c}@media(max-width:800px){.is-cert-grid{grid-template-columns:1fr}}
  </style>
</head>
<body><div class="d-flex flex-column flex-md-row" style="min-height:100vh"><?php include __DIR__.'/sidebar.php'; ?>
<main class="flex-grow-1 p-3 p-md-4 p-xl-5 bg-light"><div class="is-shell">
  <div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-3"><div><h2 class="is-title mb-1">Barangay Issuance Settings</h2><p class="text-muted mb-0">Control certificate availability, validity, privacy, verification, resident messages, and request dropdowns.</p></div><a class="btn btn-outline-secondary" href="<?= htmlspecialchars($documentSettingsBackUrl) ?>"><i class="fa-solid fa-arrow-left me-2"></i>Back to Module</a></div>
  <?php if ($documentSettingsSuccessMessage !== ''): ?><div class="alert alert-success"><?= htmlspecialchars($documentSettingsSuccessMessage) ?></div><?php endif; ?>
  <?php if ($documentSettingsErrorMessage !== ''): ?><div class="alert alert-danger"><?= htmlspecialchars($documentSettingsErrorMessage) ?></div><?php endif; ?>
  <ul class="nav nav-pills gap-2 mb-3" role="tablist">
    <li><button class="nav-link active" data-bs-toggle="pill" data-bs-target="#is-general">General</button></li><li><button class="nav-link" data-bs-toggle="pill" data-bs-target="#is-certificates">Certificates & Dropdowns</button></li><li><button class="nav-link" data-bs-toggle="pill" data-bs-target="#is-notifications">Notifications</button></li><li><button class="nav-link" data-bs-toggle="pill" data-bs-target="#is-signatories">Signatories</button></li>
  </ul>
  <div class="tab-content">
    <form method="post" action="<?= htmlspecialchars($documentSettingsActionUrl) ?>"><?= csrfTokenField() ?><input type="hidden" name="action" value="save_issuance_settings">
      <section id="is-general" class="tab-pane fade show active is-card"><div class="is-head"><h3 class="h5 mb-1">General issuance controls</h3><p class="text-muted mb-0">Changes apply to resident certificate requests and the issuance workflow.</p></div><div class="is-body">
        <div class="row g-4">
          <?php foreach ([['online_requests_enabled','Enable online certificate requests'],['first_time_job_seeker_exempt','Apply First-Time Job Seeker fee exemption'],['qr_verification_enabled','Enable QR verification'],['essential_details_only','Show only essential resident details']] as [$key,$label]): ?><div class="col-md-6"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="<?= $key ?>" id="<?= $key ?>" <?= !empty($issuanceSettings[$key])?'checked':'' ?>><label class="form-check-label fw-semibold" for="<?= $key ?>"><?= htmlspecialchars($label) ?></label></div></div><?php endforeach; ?>
          <div class="col-md-4"><label class="form-label fw-semibold">Default validity (days)</label><input class="form-control" type="number" min="1" max="365" name="default_validity_days" value="<?= (int)$issuanceSettings['default_validity_days'] ?>"></div>
          <div class="col-md-8"><label class="form-label fw-semibold">Allowed validity choices</label><div class="d-flex gap-3 flex-wrap pt-2"><?php foreach ([3,7,15,30,45,60,90,180,365] as $days): ?><label class="form-check"><input class="form-check-input" type="checkbox" name="allowed_validity_days[]" value="<?= $days ?>" <?= in_array($days,(array)$issuanceSettings['allowed_validity_days'],true)?'checked':'' ?>> <?= $days ?> days</label><?php endforeach; ?></div></div>
        </div>
      </div></section>
      <section id="is-certificates" class="tab-pane fade is-card"><div class="is-head"><h3 class="h5 mb-1">Certificate availability and request dropdowns</h3><p class="text-muted mb-0">Enter one purpose option per line. These choices are shown to residents, with “Other” supported when included.</p></div><div class="is-body is-cert-grid">
        <?php foreach (dms_issuance_certificate_catalog() as $key=>$label): $cert=$issuanceSettings['certificates'][$key]??[]; ?><div class="is-cert"><div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" name="certificate_enabled[<?= $key ?>]" id="cert_<?= $key ?>" <?= !empty($cert['enabled'])?'checked':'' ?>><label class="form-check-label fw-bold" for="cert_<?= $key ?>"><?= htmlspecialchars($label) ?></label></div><label class="form-label small fw-semibold">Purpose dropdown options</label><textarea class="form-control" rows="6" name="purpose_options[<?= $key ?>]"><?= htmlspecialchars(implode("\n",(array)($cert['purpose_options']??[]))) ?></textarea></div><?php endforeach; ?>
      </div></section>
      <section id="is-notifications" class="tab-pane fade is-card"><div class="is-head"><h3 class="h5 mb-1">Resident and admin notifications</h3><p class="text-muted mb-0">Available placeholders: {request_id}, {document_type}, {reason}, {count}, {days}.</p></div><div class="is-body">
        <?php foreach ((array)$issuanceSettings['resident_notifications'] as $event=>$notification): ?><div class="row g-2 align-items-start mb-3"><div class="col-md-3"><div class="form-check form-switch pt-2"><input class="form-check-input" type="checkbox" name="notification_enabled[<?= htmlspecialchars($event) ?>]" id="notify_<?= htmlspecialchars($event) ?>" <?= !empty($notification['enabled'])?'checked':'' ?>><label class="form-check-label fw-semibold text-capitalize" for="notify_<?= htmlspecialchars($event) ?>"><?= htmlspecialchars(str_replace('_',' ',$event)) ?></label></div></div><div class="col-md-9"><textarea class="form-control is-message" name="notification_message[<?= htmlspecialchars($event) ?>]" maxlength="500"><?= htmlspecialchars((string)$notification['message']) ?></textarea></div></div><?php endforeach; ?>
        <hr><div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" name="aging_notification_enabled" id="aging_notification_enabled" <?= !empty($issuanceSettings['aging_notification_enabled'])?'checked':'' ?>><label class="form-check-label fw-semibold" for="aging_notification_enabled">Enable admin notification for aging requests</label></div><div class="row g-3"><div class="col-md-3"><label class="form-label">Age threshold (days)</label><input class="form-control" type="number" min="1" max="90" name="aging_days" value="<?= (int)$issuanceSettings['aging_days'] ?>"></div><div class="col-md-9"><label class="form-label">Admin message</label><textarea class="form-control" name="aging_message" rows="2"><?= htmlspecialchars((string)$issuanceSettings['aging_message']) ?></textarea></div></div>
      </div></section>
      <div class="d-flex justify-content-end my-3"><button class="btn btn-primary px-4"><i class="fa-solid fa-floppy-disk me-2"></i>Save Issuance Settings</button></div>
    </form>
    <section id="is-signatories" class="tab-pane fade is-card"><div class="is-head"><h3 class="h5 mb-1">Certificate signatory</h3></div><form class="is-body" method="post" enctype="multipart/form-data" action="<?= htmlspecialchars($documentSettingsActionUrl) ?>"><?= csrfTokenField() ?><input type="hidden" name="action" value="save_document_module_settings"><?php foreach ($documentSettingsRows as $row): $key=(string)$row['signatory_key']; ?><div class="row g-3"><div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="signatory_name_<?= $key ?>" value="<?= htmlspecialchars((string)$row['name']) ?>" <?= $row['source']==='manual'?'':'readonly' ?>></div><div class="col-md-6"><label class="form-label">Title</label><input class="form-control" name="signatory_title_<?= $key ?>" value="<?= htmlspecialchars((string)$row['title']) ?>" <?= $row['source']==='manual'?'':'readonly' ?>></div><div class="col-12"><label class="form-label">Signature image</label><input class="form-control" type="file" accept="image/png,image/jpeg,image/webp" name="signature_file_<?= $key ?>"></div></div><?php endforeach; ?><div class="text-end mt-3"><button class="btn btn-primary">Save Signatory</button></div></form></section>
  </div>
</div></main></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script></body></html>
