<?php
declare(strict_types=1);
$activeCertificates=count(array_filter((array)($issuanceSettings['certificates']??[]),static fn(array $row):bool=>!empty($row['enabled'])));
$activeNotifications=count(array_filter((array)($issuanceSettings['resident_notifications']??[]),static fn(array $row):bool=>!empty($row['enabled'])));
$activeOfficials=count(array_filter($governmentOfficialRows,static fn(array $row):bool=>!empty($row['is_active'])));
$items=[
 ['General Issuance','Manage online availability, validity periods, QR verification, privacy, and the First-Time Job Seeker exemption.','fa-sliders',appUrl('Admin-End/Certificates/IssuanceGeneralSettings.php'),'General Settings',!empty($issuanceSettings['online_requests_enabled'])?'Online requests enabled':'Online requests suspended'],
 ['Certificates & Request Choices','Enable certificate types and customize the purpose choices shown on resident request forms.','fa-file-lines',appUrl('Admin-End/Certificates/IssuanceCertificateSettings.php'),'Manage Certificates',$activeCertificates.' of '.count(dms_issuance_certificate_catalog()).' active'],
 ['Indigency Recipient Directory','Manage the names, positions, offices, ordering, and availability of government officials used by Certificate of Indigency.','fa-user-tie',appUrl('Admin-End/Certificates/IndigencyRecipientSettings.php'),'Manage Directory',$activeOfficials.' active officials'],
 ['Notifications','Configure resident status messages and alerts for certificate requests that remain pending too long.','fa-bell',appUrl('Admin-End/Certificates/IssuanceNotificationSettings.php'),'Notification Settings',$activeNotifications.' of 5 events active'],
 ['Fees & Exemptions','Review certificate fees, submit fee change requests, and manage fee-related issuance rules.','fa-peso-sign',appUrl('Admin-End/Certificates/IssuanceFeeSettings.php'),'Fee Settings',!empty($issuanceSettings['first_time_job_seeker_exempt'])?'Job seeker exemption enabled':'Standard fee rules'],
];
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Barangay Issuance Settings</title><script src="https://kit.fontawesome.com/3482e00999.js" crossorigin="anonymous"></script><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="<?= htmlspecialchars(appUrl('CSS-Styles/Admin-End-CSS/AdminDashboardStyle.css')) ?>"><style>
:root{--bis-accent:#de710c;--bis-accent-deep:#9e5000}.bis-page-title{font-family:'Charis SIL Bold',serif;color:var(--bis-accent);margin-bottom:.4rem}.bis-shell{max-width:var(--admin-table-shell-max-width,1180px);margin:0 auto}.bis-panel{border:1px solid #dee2e6;border-radius:1rem;background:#fff;box-shadow:0 .125rem .25rem rgba(0,0,0,.075);padding:1.5rem}.bis-panel-head{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem;padding-bottom:1rem;margin-bottom:1rem;border-bottom:1px solid #edf0f3}.bis-panel-title{margin:0;font-size:1.1rem;font-weight:700;color:#212529}.bis-panel-copy{margin:.35rem 0 0;color:#6c757d;max-width:720px}.bis-list{display:grid;gap:.75rem}.bis-item{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:1rem;padding:1rem;border:1px solid #eceff3;border-radius:.75rem;color:#212529;text-decoration:none;transition:border-color .15s,box-shadow .15s,background-color .15s}.bis-item:hover,.bis-item:focus-visible{color:#212529;border-color:#f1b56d;background:#fffaf4;box-shadow:0 .25rem .75rem rgba(222,113,12,.08)}.bis-icon{display:inline-grid;width:2.75rem;height:2.75rem;place-items:center;border-radius:.75rem;color:var(--bis-accent);background:#fff4e8;font-size:1.1rem}.bis-title{display:block;font-size:1rem;font-weight:700}.bis-copy{display:block;margin-top:.25rem;color:#6c757d;line-height:1.45}.bis-status{display:inline-block;margin-top:.45rem;color:#747b84;font-size:.78rem}.bis-action{white-space:nowrap;color:#fff!important;background:var(--bis-accent)!important;border-color:var(--bis-accent)!important}.bis-action:hover{background:var(--bis-accent-deep)!important;border-color:var(--bis-accent-deep)!important}@media(max-width:768px){.bis-panel,.bis-item{padding:1rem}.bis-item{grid-template-columns:1fr}.bis-action{width:100%}}
</style></head><body><div class="d-flex flex-column flex-md-row" style="min-height:100vh"><?php include __DIR__.'/sidebar.php'; ?><main class="flex-grow-1 p-3 p-md-4 p-xl-5 bg-light" id="main-display"><div class="bis-shell">
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-3"><div><h1 class="bis-page-title h2">Barangay Issuance Settings</h1><p class="mb-0 text-muted">Control certificate availability, request choices, notifications, recipients, and fees.</p></div><a class="btn btn-outline-secondary" href="<?= htmlspecialchars($documentSettingsBackUrl) ?>"><i class="fa-solid fa-arrow-left me-2"></i>Back to Module</a></div><hr class="mt-0 mb-4">
<?php if($documentSettingsSuccessMessage!==''):?><div class="alert alert-success"><?= htmlspecialchars($documentSettingsSuccessMessage) ?></div><?php endif;?><?php if($documentSettingsErrorMessage!==''):?><div class="alert alert-danger"><?= htmlspecialchars($documentSettingsErrorMessage) ?></div><?php endif;?>
<section class="bis-panel"><div class="bis-panel-head"><div><h2 class="bis-panel-title">Issuance Configuration</h2><p class="bis-panel-copy">Choose the area you want to configure. Each area opens on its own focused settings page.</p></div></div><div class="bis-list">
<?php foreach($items as [$title,$copy,$icon,$url,$action,$status]):?><a class="bis-item" href="<?= htmlspecialchars($url) ?>"><span class="bis-icon"><i class="fa-solid <?= htmlspecialchars($icon) ?>"></i></span><span><span class="bis-title"><?= htmlspecialchars($title) ?></span><span class="bis-copy"><?= htmlspecialchars($copy) ?></span><span class="bis-status"><i class="fa-solid fa-circle-check me-1"></i><?= htmlspecialchars($status) ?></span></span><span class="btn bis-action"><?= htmlspecialchars($action) ?> <i class="fa-solid fa-arrow-right ms-1"></i></span></a><?php endforeach;?>
</div></section></div></main></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script></body></html>
