<?php declare(strict_types=1); ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Barangay Issuance Settings</title>
  <script src="https://kit.fontawesome.com/3482e00999.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="<?= htmlspecialchars(appUrl('CSS-Styles/Admin-End-CSS/AdminDashboardStyle.css')) ?>">
  <style>
    :root{--is-accent:#de710c;--is-accent-dark:#a95305;--is-ink:#202631;--is-muted:#68707d;--is-line:#eadfd4;--is-soft:#fff8f1;--is-bg:#f7f8fa;--is-success:#16845b}
    body{background:#f8f9fa}.is-page{width:100%}.is-title{font-family:'Charis SIL Bold',serif;color:var(--is-accent);font-size:2rem}.is-lead{color:#6c757d;max-width:820px}
    .is-hero{padding:0;background:transparent}.is-hero-actions{flex:0 0 auto}
    .is-section{border:1px solid #dee2e6;border-radius:1rem;background:#fff;box-shadow:0 .125rem .25rem rgba(0,0,0,.075);margin-bottom:1.25rem;overflow:hidden}.is-section-head{display:flex;gap:.75rem;align-items:flex-start;padding:1rem 1.25rem;border-bottom:1px solid #dee2e6;background:#fff}.is-section-icon{width:34px;height:34px;border-radius:.5rem;display:grid;place-items:center;flex:0 0 auto;background:#fff2e6;color:var(--is-accent-dark)}.is-section-title{font-size:1.05rem;font-weight:700;color:#212529;margin:0}.is-section-copy{color:#6c757d;font-size:.875rem;margin:.2rem 0 0}.is-section-body{padding:1.25rem}
    .is-toggle-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem 1.5rem}.is-toggle{display:flex;align-items:flex-start;gap:.75rem;padding:.25rem 0;cursor:pointer}.is-toggle .form-check-input{width:2.5rem;height:1.25rem;margin:.08rem 0 0;flex:0 0 auto}.is-toggle .form-check-input:checked{background-color:var(--is-accent);border-color:var(--is-accent)}.is-toggle-title{display:block;font-size:.925rem;font-weight:700;color:#212529}.is-toggle-copy{display:block;color:#6c757d;font-size:.8rem;margin-top:.15rem}
    .is-validity{display:grid;grid-template-columns:minmax(210px,.65fr) minmax(0,1.35fr);gap:1.5rem;margin-top:1.5rem;padding-top:1.25rem;border-top:1px solid #e9ecef}.is-field{padding:0}.is-field-label{font-weight:700;color:#212529;font-size:.875rem}.is-field-copy{color:#6c757d;font-size:.8rem;margin:.2rem 0 .75rem}.is-days{display:flex;gap:1rem 1.25rem;flex-wrap:wrap;padding-top:.35rem}.is-day{display:inline-flex;align-items:center;gap:.4rem}.is-day input{position:static;opacity:1;pointer-events:auto}.is-day span{display:inline;padding:0;border:0;background:transparent;color:#343a40;font-size:.875rem;font-weight:400;cursor:pointer;min-width:0}.is-day input:checked+span{color:#212529;border:0;background:transparent;box-shadow:none;font-weight:600}.is-day input:checked{background-color:var(--is-accent);border-color:var(--is-accent)}
    .is-cert-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.is-cert{border:1px solid #dee2e6;border-radius:.75rem;background:#fff;overflow:hidden}.is-cert-top{display:flex;align-items:center;justify-content:space-between;gap:.8rem;padding:.85rem 1rem;background:#f8f9fa;border-bottom:1px solid #dee2e6}.is-cert-name{font-size:.9rem;font-weight:700;color:#212529}.is-cert .form-check-input:checked{background-color:var(--is-accent);border-color:var(--is-accent)}.is-cert-body{padding:1rem}.is-options{min-height:120px;resize:vertical;font-size:.875rem;line-height:1.45;background:#fff}.is-options:focus{border-color:#e9a968;box-shadow:0 0 0 .2rem rgba(222,113,12,.11)}
    .is-notification{display:grid;grid-template-columns:190px minmax(0,1fr);gap:1rem;padding:1rem 0;border-bottom:1px solid #edf0f2}.is-notification:first-child{padding-top:0}.is-notification:last-child{border-bottom:0;padding-bottom:0}.is-message{min-height:72px;resize:vertical;font-size:.87rem}.is-placeholder{display:flex;gap:.4rem;flex-wrap:wrap;margin-bottom:1rem}.is-placeholder code{color:#8d490c;background:#fff0df;border:1px solid #f1d2b4;border-radius:7px;padding:.3rem .5rem;font-size:.76rem}
    .is-aging{margin-top:1.2rem;padding:1rem;border:1px solid #dee2e6;border-radius:.75rem;background:#f8f9fa}.is-aging-grid{display:grid;grid-template-columns:180px minmax(0,1fr);gap:1rem;margin-top:.8rem}
    .is-savebar{display:flex;justify-content:flex-end;align-items:center;gap:1rem;padding:.25rem 0 1.5rem}.is-save-note{color:#6c757d;font-size:.83rem;margin-right:auto}.btn-is-primary{color:#fff;background:var(--is-accent);border-color:var(--is-accent);font-weight:600}.btn-is-primary:hover{color:#fff;background:var(--is-accent-dark);border-color:var(--is-accent-dark)}
    .is-official-form{display:grid;grid-template-columns:1.15fr 1fr 1fr .9fr 100px auto;gap:.75rem;align-items:end}.is-official-table th{font-size:.78rem;text-transform:uppercase;letter-spacing:.03em;color:#6c757d;white-space:nowrap}.is-official-table td{vertical-align:middle}.is-official-name{font-weight:600;color:#212529}.is-official-meta{font-size:.78rem;color:#6c757d}.is-official-actions{display:flex;gap:.4rem;justify-content:flex-end;white-space:nowrap}
    @media(max-width:1100px){.is-official-form{grid-template-columns:repeat(2,minmax(0,1fr))}.is-official-form .is-official-submit{grid-column:1/-1}}
    @media(max-width:900px){.is-toggle-grid,.is-cert-grid,.is-validity{grid-template-columns:1fr}.is-notification{grid-template-columns:1fr;gap:.55rem}.is-aging-grid{grid-template-columns:1fr}}
    @media(max-width:576px){.is-section-body{padding:1rem}.is-section-head{padding:1rem}.is-save-note{display:none}.is-savebar .btn{width:100%}.is-hero-actions{width:100%}.is-hero-actions .btn{width:100%}}
  </style>
</head>
<body><div class="d-flex flex-column flex-md-row" style="min-height:100vh"><?php include __DIR__.'/sidebar.php'; ?>
<main class="flex-grow-1 p-3 p-md-4 bg-light" id="main-display"><div class="is-page">
  <header class="is-hero"><div><h1 class="is-title mb-2">Manage Issuance Settings</h1><p class="is-lead mb-0">Manage certificate availability, validity, verification, resident messages, and request choices.</p></div></header>
  <hr class="mt-3 mb-4">
  <?php if ($documentSettingsSuccessMessage !== ''): ?><div class="alert alert-success mt-3 mb-0"><i class="fa-solid fa-circle-check me-2"></i><?= htmlspecialchars($documentSettingsSuccessMessage) ?></div><?php endif; ?>
  <?php if ($documentSettingsErrorMessage !== ''): ?><div class="alert alert-danger mt-3 mb-0"><i class="fa-solid fa-triangle-exclamation me-2"></i><?= htmlspecialchars($documentSettingsErrorMessage) ?></div><?php endif; ?>
  <form method="post" action="<?= htmlspecialchars($documentSettingsActionUrl) ?>" id="issuanceSettingsForm"><?= csrfTokenField() ?><input type="hidden" name="action" value="save_issuance_settings">
    <section class="is-section" id="general"><div class="is-section-head"><span class="is-section-icon"><i class="fa-solid fa-sliders"></i></span><div><h2 class="is-section-title">General issuance controls</h2><p class="is-section-copy">Set the rules applied across online certificate requests and document generation.</p></div></div><div class="is-section-body">
      <div class="is-toggle-grid">
        <?php $toggles=[['online_requests_enabled','Online certificate requests','Allow residents to submit certificate applications online.'],['first_time_job_seeker_exempt','First-Time Job Seeker exemption','Automatically treat eligible first-time job seeker requests as fee-exempt.'],['qr_verification_enabled','QR verification','Allow scans to verify certificates from this department. QR codes remain printed when disabled.'],['essential_details_only','Essential resident details only','Limit certificate views to information needed for processing.'],['copy_has_signature','Resident copy signature','Show the uploaded official signature on the resident certificate copy.'],['print_header_enabled','Add barangay header when printed','Turn off when using bond paper that already has the barangay letterhead.']]; foreach($toggles as [$key,$title,$copy]): ?><label class="is-toggle" for="<?= $key ?>"><input class="form-check-input" type="checkbox" name="<?= $key ?>" id="<?= $key ?>" <?= !empty($issuanceSettings[$key])?'checked':'' ?>><span><span class="is-toggle-title"><?= htmlspecialchars($title) ?></span><span class="is-toggle-copy"><?= htmlspecialchars($copy) ?></span></span></label><?php endforeach; ?>
      </div>
      <div class="mt-4 pt-4 border-top"><div class="is-field-label">Generated document fields</div><p class="is-field-copy">Turn each field on or off on generated certificate documents and PDFs.</p><div class="is-toggle-grid">
        <?php foreach(dms_document_field_catalog('issuance') as $fieldKey=>$fieldLabel): ?><label class="is-toggle"><input class="form-check-input" type="checkbox" name="document_field_visible[<?= htmlspecialchars($fieldKey) ?>]" <?= !empty($issuanceSettings['document_field_visibility'][$fieldKey])?'checked':'' ?>><span><span class="is-toggle-title">Show <?= htmlspecialchars($fieldLabel) ?></span></span></label><?php endforeach; ?>
      </div></div>
      <div class="is-validity"><div class="is-field"><label class="is-field-label" for="default_validity_days">Default validity</label><p class="is-field-copy">Used when staff do not choose another period.</p><div class="input-group"><input class="form-control" id="default_validity_days" type="number" min="1" max="365" name="default_validity_days" value="<?= (int)$issuanceSettings['default_validity_days'] ?>"><span class="input-group-text">days</span></div></div><div class="is-field"><div class="is-field-label">Allowed validity choices</div><p class="is-field-copy">Choose the periods staff can select during approval and manual issuance.</p><div class="is-days"><?php foreach([3,7,15,30,45,60,90,180,365] as $days): ?><label class="is-day"><input type="checkbox" name="allowed_validity_days[]" value="<?= $days ?>" <?= in_array($days,(array)$issuanceSettings['allowed_validity_days'],true)?'checked':'' ?>><span><?= $days ?> days</span></label><?php endforeach; ?></div></div></div>
    </div></section>

    <section class="is-section" id="certificates"><div class="is-section-head"><span class="is-section-icon"><i class="fa-solid fa-file-lines"></i></span><div><h2 class="is-section-title">Certificates and request choices</h2><p class="is-section-copy">Control availability and customize the purpose dropdown for every supported certificate.</p></div></div><div class="is-section-body"><div class="is-cert-grid">
      <?php foreach(dms_issuance_certificate_catalog() as $key=>$label): $cert=$issuanceSettings['certificates'][$key]??[]; ?><article class="is-cert"><div class="is-cert-top"><span class="is-cert-name"><?= htmlspecialchars($label) ?></span><div class="form-check form-switch m-0"><input class="form-check-input" type="checkbox" name="certificate_enabled[<?= $key ?>]" id="cert_<?= $key ?>" <?= !empty($cert['enabled'])?'checked':'' ?> aria-label="Enable <?= htmlspecialchars($label) ?>"></div></div><div class="is-cert-body"><label class="form-label small fw-bold" for="options_<?= $key ?>">Purpose dropdown options</label><p class="small text-muted mb-2">One option per line. Include “Other” to allow a custom answer.</p><textarea class="form-control is-options" id="options_<?= $key ?>" name="purpose_options[<?= $key ?>]"><?= htmlspecialchars(implode("\n",(array)($cert['purpose_options']??[]))) ?></textarea></div></article><?php endforeach; ?>
    </div></div></section>

    <section class="is-section" id="notifications"><div class="is-section-head"><span class="is-section-icon"><i class="fa-solid fa-bell"></i></span><div><h2 class="is-section-title">Notifications</h2><p class="is-section-copy">Choose which status updates residents receive and customize the message for each event.</p></div></div><div class="is-section-body"><div class="is-placeholder"><code>{request_id}</code><code>{document_type}</code><code>{reason}</code><code>{count}</code><code>{days}</code></div>
      <?php foreach((array)$issuanceSettings['resident_notifications'] as $event=>$notification): ?><div class="is-notification"><div><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="notification_enabled[<?= htmlspecialchars($event) ?>]" id="notify_<?= htmlspecialchars($event) ?>" <?= !empty($notification['enabled'])?'checked':'' ?>><label class="form-check-label fw-bold text-capitalize" for="notify_<?= htmlspecialchars($event) ?>"><?= htmlspecialchars(str_replace('_',' ',$event)) ?></label></div><div class="small text-muted mt-1">Resident status update</div></div><textarea class="form-control is-message" name="notification_message[<?= htmlspecialchars($event) ?>]" maxlength="500" aria-label="<?= htmlspecialchars(str_replace('_',' ',$event)) ?> message"><?= htmlspecialchars((string)$notification['message']) ?></textarea></div><?php endforeach; ?>
      <div class="is-aging"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="aging_notification_enabled" id="aging_notification_enabled" <?= !empty($issuanceSettings['aging_notification_enabled'])?'checked':'' ?>><label class="form-check-label fw-bold" for="aging_notification_enabled">Admin notification for aging requests</label></div><p class="small text-muted mb-0 mt-1">Alert administrators when certificate requests remain pending beyond the threshold.</p><div class="is-aging-grid"><div><label class="form-label small fw-bold" for="aging_days">Threshold</label><div class="input-group"><input class="form-control" id="aging_days" type="number" min="1" max="90" name="aging_days" value="<?= (int)$issuanceSettings['aging_days'] ?>"><span class="input-group-text">days</span></div></div><div><label class="form-label small fw-bold" for="aging_message">Admin message</label><textarea class="form-control" id="aging_message" name="aging_message" rows="2"><?= htmlspecialchars((string)$issuanceSettings['aging_message']) ?></textarea></div></div></div>
    </div></section>

    <div class="is-savebar mb-3"><span class="is-save-note"><i class="fa-solid fa-shield-halved me-2 text-success"></i>Changes are audit logged and apply after saving.</span><button class="btn btn-is-primary px-4" type="submit"><i class="fa-solid fa-floppy-disk me-2"></i>Save Issuance Settings</button></div>
  </form>

  <section class="is-section" id="indigency-officials"><div class="is-section-head"><span class="is-section-icon"><i class="fa-solid fa-user-tie"></i></span><div><h2 class="is-section-title">Certificate of Indigency — Government Officials</h2><p class="is-section-copy">Manage the officials shown in the “To be submitted to” dropdown. Changes are immediately available on the resident request form.</p></div></div><div class="is-section-body">
    <h3 class="h6 fw-bold mb-3">Add government official</h3>
    <form class="is-official-form mb-4" id="indigencyOfficialForm" method="post" action="<?= htmlspecialchars($documentSettingsActionUrl) ?>"><?= csrfTokenField() ?><input type="hidden" name="action" value="save_indigency_government_official"><input type="hidden" name="government_official_id" id="indigencyOfficialId" value="0">
      <div><label class="form-label small fw-semibold">Name</label><input class="form-control" id="indigencyOfficialName" name="official_name" required placeholder="e.g. Hon. Juan Dela Cruz"></div>
      <div><label class="form-label small fw-semibold">Position</label><input class="form-control" id="indigencyOfficialPosition" name="position_name" required placeholder="e.g. Municipal Mayor"></div>
      <div><label class="form-label small fw-semibold">Office / Jurisdiction</label><input class="form-control" id="indigencyOfficialLocation" name="jurisdiction_location" required placeholder="e.g. Rodriguez, Rizal"></div>
      <div><label class="form-label small fw-semibold">Office group</label><select class="form-select" id="indigencyOfficialGroup" name="group_key" required><option value="president">President</option><option value="vice_president">Vice President</option><option value="senate">Senate</option><option value="rizal_officials">Rizal Officials</option><option value="municipal_officials" selected>Rodriguez Municipal Officials</option></select></div>
      <div><label class="form-label small fw-semibold">Order</label><input class="form-control" id="indigencyOfficialOrder" type="number" min="0" max="9999" name="display_order" value="0"></div>
      <div class="is-official-submit"><div class="form-check mb-2 d-none" id="indigencyOfficialActiveWrap"><input class="form-check-input" type="checkbox" name="is_active" id="indigencyOfficialActive" checked><label class="form-check-label small" for="indigencyOfficialActive">Active</label></div><button class="btn btn-is-primary w-100" id="indigencyOfficialSubmit"><i class="fa-solid fa-plus me-2"></i>Add</button><button class="btn btn-outline-secondary w-100 mt-2 d-none" type="button" id="indigencyOfficialCancel">Cancel</button></div>
    </form>
    <div class="table-responsive"><table class="table table-hover align-middle is-official-table mb-0"><thead><tr><th>Name</th><th>Position</th><th>Office / Jurisdiction</th><th>Group</th><th>Order</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
      <?php if ($governmentOfficialRows === []): ?><tr><td colspan="7" class="text-center text-muted py-4">No government officials configured.</td></tr><?php endif; ?>
      <?php foreach($governmentOfficialRows as $official): $officialId=(int)$official['government_official_id']; ?><tr><td><span class="is-official-name"><?= htmlspecialchars((string)$official['official_name']) ?></span></td><td><?= htmlspecialchars((string)$official['position_name']) ?></td><td><?= htmlspecialchars((string)$official['jurisdiction_location']) ?></td><td><span class="is-official-meta"><?= htmlspecialchars(ucwords(str_replace('_',' ',(string)$official['group_key']))) ?></span></td><td><?= (int)$official['display_order'] ?></td><td><?= !empty($official['is_active'])?'<span class="badge text-bg-success">Active</span>':'<span class="badge text-bg-secondary">Inactive</span>' ?></td><td><div class="is-official-actions"><button type="button" class="btn btn-sm btn-outline-primary" data-official-edit data-id="<?= $officialId ?>" data-name="<?= htmlspecialchars((string)$official['official_name'],ENT_QUOTES,'UTF-8') ?>" data-position="<?= htmlspecialchars((string)$official['position_name'],ENT_QUOTES,'UTF-8') ?>" data-location="<?= htmlspecialchars((string)$official['jurisdiction_location'],ENT_QUOTES,'UTF-8') ?>" data-group="<?= htmlspecialchars((string)$official['group_key'],ENT_QUOTES,'UTF-8') ?>" data-order="<?= (int)$official['display_order'] ?>" data-active="<?= !empty($official['is_active'])?'1':'0' ?>"><i class="fa-solid fa-pen"></i></button><form method="post" action="<?= htmlspecialchars($documentSettingsActionUrl) ?>" onsubmit="return confirm('Delete this government official from the dropdown?');"><?= csrfTokenField() ?><input type="hidden" name="action" value="delete_indigency_government_official"><input type="hidden" name="government_official_id" value="<?= $officialId ?>"><button class="btn btn-sm btn-outline-danger" aria-label="Delete"><i class="fa-solid fa-trash"></i></button></form></div></td></tr><?php endforeach; ?>
    </tbody></table></div>
  </div></section>
</div></main></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script>
(() => {
  const form = document.getElementById('indigencyOfficialForm');
  if (!form) return;
  const fields = {
    id: document.getElementById('indigencyOfficialId'), name: document.getElementById('indigencyOfficialName'),
    position: document.getElementById('indigencyOfficialPosition'), location: document.getElementById('indigencyOfficialLocation'),
    group: document.getElementById('indigencyOfficialGroup'), order: document.getElementById('indigencyOfficialOrder'),
    active: document.getElementById('indigencyOfficialActive')
  };
  const submit = document.getElementById('indigencyOfficialSubmit');
  const cancel = document.getElementById('indigencyOfficialCancel');
  const activeWrap = document.getElementById('indigencyOfficialActiveWrap');
  const reset = () => { form.reset(); fields.id.value='0'; fields.group.value='municipal_officials'; fields.order.value='0'; fields.active.checked=true; activeWrap.classList.add('d-none'); cancel.classList.add('d-none'); submit.innerHTML='<i class="fa-solid fa-plus me-2"></i>Add'; };
  document.querySelectorAll('[data-official-edit]').forEach((button) => button.addEventListener('click', () => {
    fields.id.value=button.dataset.id||'0'; fields.name.value=button.dataset.name||''; fields.position.value=button.dataset.position||''; fields.location.value=button.dataset.location||''; fields.group.value=button.dataset.group||'municipal_officials'; fields.order.value=button.dataset.order||'0'; fields.active.checked=button.dataset.active==='1'; activeWrap.classList.remove('d-none'); cancel.classList.remove('d-none'); submit.innerHTML='<i class="fa-solid fa-floppy-disk me-2"></i>Update'; form.scrollIntoView({behavior:'smooth',block:'center'}); fields.name.focus();
  }));
  cancel.addEventListener('click', reset);
})();
</script></body></html>
