-- Unified resident transaction ledger.
-- transaction_id format: MMYYYYXXXX (generated by GenerateTransactionID()).

CREATE TABLE IF NOT EXISTS residenttransactiontbl (
  transaction_id VARCHAR(10) NOT NULL,
  user_id VARCHAR(12) NOT NULL,
  resident_user_id VARCHAR(12) DEFAULT NULL,
  source_type VARCHAR(50) NOT NULL,
  source_id VARCHAR(64) NOT NULL,
  transaction_type VARCHAR(50) NOT NULL,
  title VARCHAR(160) NOT NULL,
  details TEXT DEFAULT NULL,
  metadata_json JSON DEFAULT NULL,
  amount DECIMAL(12,2) DEFAULT NULL,
  payment_method VARCHAR(40) DEFAULT NULL,
  or_number VARCHAR(60) DEFAULT NULL,
  payment_deadline DATETIME DEFAULT NULL,
  payment_timestamp DATETIME DEFAULT NULL,
  status_id INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  reviewed_by VARCHAR(12) DEFAULT NULL,
  reviewed_at DATETIME DEFAULT NULL,
  released_by VARCHAR(12) DEFAULT NULL,
  released_at DATETIME DEFAULT NULL,
  PRIMARY KEY (transaction_id),
  UNIQUE KEY uq_source (source_type, source_id, transaction_type),
  UNIQUE KEY uq_or_number (or_number),
  KEY idx_user_id (user_id),
  KEY idx_resident_user_id (resident_user_id),
  KEY idx_source (source_type, source_id),
  KEY idx_status_id (status_id),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
